# Generated by Django 4.1.3 on 2022-11-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proj',
            options={'permissions': (('add_user', 'can add user to project in same organization'),)},
        ),
    ]
