# Generated by Django 4.1.3 on 2022-11-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_alter_proj_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'permissions': (('add_user_', 'can add user to organization'), ('remove_user', 'can remove user from organization'))},
        ),
    ]
