# Generated by Django 4.1.3 on 2022-11-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_alter_org_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'permissions': (('add_user', 'can add user to organization'), ('remove_user', 'can remove user from organization'), ('assign_manager', 'can assign prog_manager role to user'))},
        ),
        migrations.AlterField(
            model_name='proj',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.org'),
        ),
    ]
