# Generated by Django 4.1.3 on 2022-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT', '0004_alter_virtualdevice_blood_sugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdevice',
            name='blood_sugar',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='virtualdevice',
            name='heater',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='virtualdevice',
            name='temp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
