# Generated by Django 4.1.3 on 2022-11-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.org'),
        ),
        migrations.AddField(
            model_name='user',
            name='projs',
            field=models.ManyToManyField(null=True, related_name='users', to='Organization.proj'),
        ),
    ]
