# Generated by Django 4.1.3 on 2022-11-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('User', '0002_user_org_user_projs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projs',
            field=models.ManyToManyField(blank=True, related_name='users', to='Organization.proj'),
        ),
    ]
